Repository meilisearch/meilisearch-js, pull requests merged in 2020-07, with the labels that each got.

#488 Update tests according to bump meilisearch v0.12.0
  tests/client_tests.ts
  tests/settings_tests.ts
Labels: skip-changelog

#517 Improve examples and their READMEs
  examples/browser/README.md
  examples/browser/index.html
  examples/node/README.md
  examples/node/search_example.js
  examples/node/small_index.js
  examples/typescript-browser/README.md
  examples/typescript-browser/src/index.ts
  examples/typescript-node/README.md
Labels: SDK JS, documentation

#520 Update release drafter config to remove dependabot
  .github/release-draft-template.yml
Labels: skip-changelog

#530 Settings changes
  .code-samples.meilisearch.yaml
  README.md
  src/index.ts
  src/types.ts
  tests/accept_new_fields_tests.ts
  tests/displayed_attributes_tests.ts
  tests/get_or_create_tests.ts
  tests/searchable_attributes_tests.ts
  tests/settings_tests.ts
Labels: breaking-change

#528 Remove sys-info and sys-info pretty
  .code-samples.meilisearch.yaml
  README.md
  src/meilisearch.ts
  src/types.ts
  tests/client_tests.ts
Labels: breaking-change
