Repository meilisearch/meilisearch-js, pull requests merged in 2020-09, with the labels that each got.

#562 MeiliSearch Bump to v0.14.0
  README.md
  tests/index_tests.ts
Labels: MeiliSearch Bump

#572 Update package version
  package.json
Labels: skip-changelog

#573 Remove axios and change browser bundle name
  README.md
  examples/browser/index.html
  examples/node/search_example.js
  examples/node/small_index.js
  jest.config.js
  package.json
  rollup.config.js
  src/errors/http-error-handler.ts
  src/errors/meilisearch-api-error.ts
  src/errors/meilisearch-communication-error.ts
  src/http-requests.ts
  src/index.ts
  src/meili-axios-wrapper.ts
  src/meilisearch.ts
  src/types.ts
  tests/index_tests.ts
  tsconfig.json
  yarn.lock
Labels: breaking-change

#598 Upgrade to v14
  package.json
Labels: skip-changelog
