Repository meilisearch/meilisearch-js, pull requests merged in 2021-10, with the labels that each got.

#1016 refactor(#920): Update the method names
  README.md
  src/lib/meilisearch.ts
  tests/client_tests.ts
Labels: hacktoberfest-accepted

#1017 refactor(#921): Update the params order
  src/lib/indexes.ts
  src/lib/meilisearch.ts
Labels: breaking-change, hacktoberfest-accepted

#1022 Changes name of listIndexes to getIndexes
  .code-samples.meilisearch.yaml
  README.md
  src/lib/meilisearch.ts
  tests/client_tests.ts
  tests/documents_tests.ts
  tests/env/browser/index.html
  tests/env/typescript-browser/src/index.ts
  tests/env/typescript-node/src/index.ts
  tests/index_tests.ts
  tests/meilisearch-test-utils.ts
Labels: breaking-change, hacktoberfest-accepted

#1020 Fix grammar issues in README
  README.md
Labels: skip-changelog, hacktoberfest-accepted

#1019 Update version for the next release (v0.22.0)
  package.json
Labels: skip-changelog

#1027 Add http protocol at the beginning of the URL if not present
  src/lib/meilisearch.ts
  src/lib/utils.ts
  tests/client_tests.ts
Labels: breaking-change
