Repository meilisearch/meilisearch-js, pull requests merged in 2022-06, with the labels that each got.

#1246 Fix return statement in jsdoc comment
  src/lib/indexes.ts
Labels: skip-changelog

#1249 Update primary key code-samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#1245 Rework the custom Meilisearch Errors
  .github/dependabot.yml
  jest.config.js
  package.json
  src/errors/http-error-handler.ts
  src/errors/meilisearch-api-error.ts
  src/errors/meilisearch-communication-error.ts
  src/errors/meilisearch-error.ts
  src/errors/meilisearch-timeout-error.ts
  src/lib/http-requests.ts
  src/types/types.ts
  tests/client_tests.ts
  tests/errors_tests.ts
  tests/index_tests.ts
  tsconfig.json
  yarn.lock
Labels: breaking-change

#1256 Allow query in search options
  src/indexes.ts
  src/types/types.ts
  tests/search.test.ts
  tests/typed_search.test.ts
Labels: breaking-change

#1261 Wrap get indexes routes in results object v0.28
  README.md
  src/clients/client.ts
  src/indexes.ts
  src/types/types.ts
  tests/client.test.ts
  tests/index.test.ts
  tests/utils/meilisearch-test-utils.ts
Labels: breaking-change

#1264 Update documents method v0.28
  README.md
  playgrounds/javascript/src/app.js
  src/indexes.ts
  src/types/types.ts
  tests/documents.test.ts
Labels: breaking-change

#1266 Update key management v0.28
  README.md
  src/clients/client.ts
  src/types/types.ts
  tests/keys.test.ts
Labels: breaking-change

#1271 Update waitForTasks return format to not use resource result
  README.md
  src/clients/client.ts
  src/indexes.ts
  src/task.ts
  tests/wait_for_task.test.ts
Labels: breaking-change

#1274 Add prototype setting for meili errors to allow instanceof operator
  src/errors/meilisearch-api-error.ts
  src/errors/meilisearch-communication-error.ts
  src/errors/meilisearch-error.ts
  src/errors/meilisearch-timeout-error.ts
  tests/errors.test.ts
Labels: enhancement

#1276 fix: TypoTolerance type has a wrong key name
  src/types/types.ts
Labels: bug

#1268 Update token creation v0.28.0
  src/clients/client.ts
  src/clients/node-client.ts
  src/token.ts
  src/utils.ts
  tests/token.test.ts
Labels: breaking-change

#1269 Add pagination system on resources for v0.28.0
  README.md
  src/clients/client.ts
  src/indexes.ts
  src/task.ts
  src/types/types.ts
  tests/documents.test.ts
  tests/env/typescript-browser/src/index.ts
  tests/env/typescript-node/src/index.ts
  tests/index.test.ts
  tests/keys.test.ts
  tests/task.test.ts
Labels: breaking-change

#1281 Add pagination and faceting types on settings for v0.28.0
  src/types/types.ts
  tests/settings.test.ts
Labels: enhancement

#1272 Add client header with package information
  .github/scripts/check-release.sh
  CONTRIBUTING.md
  src/http-requests.ts
  src/package-version.ts
  src/types/types.ts
  tests/client.test.ts
Labels: enhancement
