Repository meilisearch/meilisearch-js, pull requests merged in 2022-10, with the labels that each got.

#1338 refactor: Construct date type for related keys
  src/clients/client.ts
  src/indexes.ts
  src/task.ts
  src/types/types.ts
  tests/keys.test.ts
  tests/task.test.ts
Labels: breaking-change

#1343 Refactor Task and EnqueuedTask to classes
  src/clients/client.ts
  src/enqueued-task.ts
  src/http-requests.ts
  src/indexes.ts
  src/task.ts
  src/types/types.ts
  tests/get_search.test.ts
  tests/ranking_rules.test.ts
  tests/search.test.ts
  tests/stop_words.test.ts
  tests/typed_search.test.ts
Labels: breaking-change

#1344 Add faceting index settings methods
  .code-samples.meilisearch.yaml
  README.md
  src/indexes.ts
  tests/faceting.test.ts
  tests/settings.test.ts
Labels: enhancement

#1339 Add support to the pagination setting customization at the index level
  .code-samples.meilisearch.yaml
  README.md
  src/indexes.ts
  tests/pagination.test.ts
  tests/settings.test.ts
Labels: enhancement

#1347 Standardise naming convention of Private and Public keys in test to Admin and Search respectively.
  tests/client.test.ts
  tests/displayed_attributes.test.ts
  tests/distinct_attribute.test.ts
  tests/documents.test.ts
  tests/dump.test.ts
  tests/faceting.test.ts
  tests/filterable_attributes.test.ts
  tests/get_search.test.ts
  tests/index.test.ts
  tests/keys.test.ts
  tests/pagination.test.ts
  tests/ranking_rules.test.ts
  tests/search.test.ts
  tests/searchable_attributes.test.ts
  tests/settings.test.ts
  tests/sortable_attributes.test.ts
  tests/stop_words.test.ts
  tests/synonyms.test.ts
  tests/task.test.ts
  tests/token.test.ts
  tests/typed_search.test.ts
  tests/typo_tolerance.test.ts
  tests/utils/meilisearch-test-utils.ts
  tests/wait_for_task.test.ts
Labels: skip-changelog

#1355 Update version for the next release (v0.29.0)
  package.json
  src/package-version.ts
Labels: skip-changelog

#1357 Changed MEILISEARCH_HOST to MEILISEARCH_URL
  docker-compose.yml
  tests/utils/meilisearch-test-utils.ts
Labels: skip-changelog

#1371 docs: add parameter samples in v0.29 release
  .code-samples.meilisearch.yaml
Labels: skip-changelog
