Repository meilisearch/meilisearch-js, pull requests merged in 2022-11, with the labels that each got.

#1377 Export Task and EnqueuedTask
  src/index.ts
Labels: bug

#1378 Update version for the next release (v0.29.1)
  package.json
  src/package-version.ts
Labels: skip-changelog

#1372 Add pagination feature for v0.30.0
  CONTRIBUTING.md
  src/types/types.ts
  tests/get_search.test.ts
  tests/search.test.ts
  tests/typed_search.test.ts
Labels: enhancement

#1379 Add task cancel API for v0.30.0
  README.md
  src/clients/client.ts
  src/task.ts
  src/types/types.ts
  tests/task.test.ts
Labels: enhancement

#1388 Remove batch uid for v0.30.0
  src/task.ts
  src/types/types.ts
Labels: breaking-change

#1386 Add matchedDocuments in task details for v0.30.0
  src/types/types.ts
  tests/documents.test.ts
Labels: breaking-change

#1385 Add missing master key error code for v0.30.0
  src/types/types.ts
Labels: enhancement

#1382 Add delete task api for v0.30.0
  README.md
  src/clients/client.ts
  src/task.ts
  src/types/types.ts
  tests/task.test.ts
Labels: enhancement

#1384 Add swap indexes feature for v0.30.0
  README.md
  src/clients/client.ts
  src/types/types.ts
  tests/client.test.ts
Labels: enhancement

#1402 Rename setting detail original filters to original filter for v0.30.0
  src/types/types.ts
  tests/task.test.ts
Labels: skip-changelog

#1398 Make all the fields of details field of TaskObject optional
  src/types/types.ts
Labels: breaking-change

#1401 Add setting detail providedIds for v0.30.0
  src/types/types.ts
  tests/documents.test.ts
Labels: skip-changelog

#1411 Fix canceled by code sample
  .code-samples.meilisearch.yaml
Labels: skip-changelog
