Repository meilisearch/meilisearch-js, pull requests merged in 2022-04, with the labels that each got.

#1193 Avoid duplication in tests
  package.json
  tests/displayed_attributes_tests.ts
  tests/distinct_attribute_tests.ts
  tests/documents_tests.ts
  tests/filterable_attributes_tests.ts
  tests/ranking_rules_tests.ts
  tests/searchable_attributes_tests.ts
  tests/settings_tests.ts
  tests/sortable_attributes_tests.ts
  tests/stop_words_tests.ts
  tests/synonyms_tests.ts
  tests/task_tests.ts
  tests/wait_for_task.ts
Labels: skip-changelog

#1194 Create union between search parameters types
  src/types/types.ts
Labels: enhancement, skip-changelog

#1195 Fix cropping tests
  tests/get_search_tests.ts
  tests/search_tests.ts
  tests/typed_search_tests.ts
Labels: skip-changelog

#1196 Add new search parameters highlightPreTag, highlightPostTag and cropMarker
  src/types/types.ts
  tests/get_search_tests.ts
  tests/search_tests.ts
Labels: enhancement

#1203 Fix version naming in beta release explaination
  CONTRIBUTING.md
Labels: skip-changelog

#1207 Update wrong naming inside typotolerance setting
  tests/settings_tests.ts
  tests/typo_tolerance_tests.ts
Labels: skip-changelog

#1209 Make updateDocuments accept partial documents in typing
  README.md
  src/lib/indexes.ts
  tests/documents_tests.ts
  tests/meilisearch-test-utils.ts
Labels: bug

#1208 Update the code samples with highlight and crop
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#1210 Fix getDocument code sample for documenation
  .code-samples.meilisearch.yaml
Labels: skip-changelog
