Repository meilisearch/meilisearch-js, pull requests merged in 2023-05, with the labels that each got.

#1488 Add conditional loading for cross-fetch/polyfill - favour native fetch
  package.json
  src/errors/meilisearch-communication-error.ts
  src/http-requests.ts
  tests/env/node/getting_started.js
Labels: enhancement

#1493 Add the filter field in getDocuments for Meilisearch v1.2
  .eslintrc.js
  src/errors/index.ts
  src/errors/version-hint-message.ts
  src/indexes.ts
  src/types/types.ts
  tests/documents.test.ts
Labels: enhancement

#1499 Remove conditionnal loading for fetch polyfill
  src/errors/meilisearch-communication-error.ts
  src/http-requests.ts
Labels: bug

#1498 Fix broken link
  README.md
Labels: documentation, maintenance

#1503 Feat/native fetch with nitro support
  package.json
  src/errors/meilisearch-communication-error.ts
  src/http-requests.ts
  tests/env/nitro-app/.gitignore
  tests/env/nitro-app/package.json
  tests/env/nitro-app/routes/index.js
  tests/env/nitro-app/tests/client.test.js
  tests/env/nitro-app/yarn.lock
Labels: bug
