Repository meilisearch/meilisearch-js, pull requests merged in 2023-03, with the labels that each got.

#1454 Add additional tests on pagination typing
  tests/search.test.ts
Labels: skip-changelog

#1458 Add multi search method of Meilisearch v1.1
  README.md
  src/clients/client.ts
  src/types/types.ts
  tests/search.test.ts
Labels: enhancement

#1465 Fix pre-release CI not triggering
  .github/workflows/pre-release-tests.yml
Labels: skip-changelog

#1466 Update puppeteer versions
  tests/env/express/package.json
  tests/env/express/yarn.lock
Labels: skip-changelog, maintenance

#1464 Add MultiSearchQuery and MultiSearchResult types
  src/types/types.ts
Labels: skip-changelog

#1467 Add building of the project before running the browser tests
  package.json
Labels: skip-changelog

#1461 feat: added support for custom request config
  README.md
  src/clients/browser-client.ts
  src/http-requests.ts
  src/types/types.ts
  tests/client.test.ts
Labels: breaking-change

#1470 Remove min max being optional in facetStats results
  src/types/types.ts
  tests/search.test.ts
Labels: skip-changelog
