Repository meilisearch/meilisearch-js, pull requests merged in 2023-02, with the labels that each got.

#1436 Add tests on primary key inference for v1.0.0 of Meilisearch
  tests/documents.test.ts
Labels: skip-changelog

#1444 Update typescript to 4.9.5 (ts)
  .eslintignore
  .eslintrc.js
  package.json
  src/clients/client.ts
  tests/search.test.ts
  tsconfig.json
  yarn.lock
Labels: bug

#1445 Update version for the next release (v0.31.1)
  package.json
  src/package-version.ts
Labels: skip-changelog

#1451 Fix wrong naming in docker prototype script
  .github/scripts/prototype-docker-version.sh
Labels: skip-changelog

#1446 Ensure the document type provided to the search method is a Record
  src/indexes.ts
Labels: skip-changelog

#1435 Make `SearchResponse` types more strict regarding to pagination
  src/indexes.ts
  src/types/types.ts
  tests/search.test.ts
Labels: breaking-change
