Repository meilisearch/meilisearch-js, pull requests merged in 2023-04, with the labels that each got.

#1474 Add method to add/update documents from a string
  README.md
  src/http-requests.ts
  src/indexes.ts
  src/types/types.ts
  tests/raw_document.test.ts
Labels: enhancement

#1479 Fix multiSearch to allow using host config with path
  src/clients/client.ts
Labels: bug

#1482 remove PUT on contentType enum
  src/types/types.ts
Labels: skip-changelog

#1485 client.stats() isn't a function in the latest release, it seems `client.getStats()` is the correct function.
  .code-samples.meilisearch.yaml
Labels: skip-changelog
