Repository meilisearch/meilisearch-js, pull requests merged in 2023-06, with the labels that each got.

#1510 Remove the `jsdoc` eslint plugin
  .eslintrc.js
  package.json
  yarn.lock
Labels: skip-changelog

#1455 fix(type): getTypoTolerance return value type
  src/indexes.ts
Labels: bug

#1518 Fix get typo tolerance return type
  src/indexes.ts
  tests/typo_tolerance.test.ts
Labels: skip-changelog

#1522 Change target in tsconfig to ES6
  tsconfig.json
Labels: breaking-change

#1524 Fix Key type param typos.
  src/clients/client.ts
  src/types/types.ts
  tests/keys.test.ts
Labels: bug
