Repository meilisearch/meilisearch-js, pull requests merged in 2024-10, with the labels that each got.

#1733 Update check-release.sh following format
  .github/scripts/check-release.sh
Labels: maintenance

#1694 Switch test runner from Jest to Vitest
  .eslintrc.js
  eslint.config.js
  package.json
  tests/__snapshots__/facet_search.test.ts.snap
  tests/__snapshots__/faceting.test.ts.snap
  tests/__snapshots__/get_search.test.ts.snap
  tests/__snapshots__/search.test.ts.snap
  tests/__snapshots__/settings.test.ts.snap
  tests/client.test.ts
  tests/dictionary.test.ts
  tests/displayed_attributes.test.ts
  tests/distinct_attribute.test.ts
  tests/documents.test.ts
  tests/dump.test.ts
  tests/embedders.test.ts
  tests/errors.test.ts
  tests/facet_search.test.ts
  tests/faceting.test.ts
  tests/filterable_attributes.test.ts
  tests/get_search.test.ts
  tests/index.test.ts
  tests/keys.test.ts
  tests/localized_attributes.test.ts
  tests/non_separator_tokens.test.ts
  tests/pagination.test.ts
  tests/proximity_precision.test.ts
  tests/ranking_rules.test.ts
  tests/raw_document.test.ts
  tests/search.test.ts
  tests/search_cutoff_ms.test.ts
  tests/searchable_attributes.test.ts
  tests/separator_tokens.test.ts
  tests/settings.test.ts
  tests/snapshots.test.ts
  tests/sortable_attributes.test.ts
  tests/stop_words.test.ts
  tests/synonyms.test.ts
  tests/task.test.ts
  tests/token.test.ts
  tests/typed_search.test.ts
  tests/typo_tolerance.test.ts
  tests/unit.test.ts
  tests/wait_for_task.test.ts
  vitest.config.js
  yarn.lock
Labels: maintenance

#1611 Add `package.json` `"exports"` field
  package.json
  rollup.config.js
  scripts/build.js
  scripts/file-size.js
  src/token.ts
  tests/env/esm/webpack.config.js
  tests/env/nitro-app/tests/client.test.js
  tests/env/typescript-browser/webpack.config.js
  tests/token.test.ts
  yarn.lock
Labels: breaking-change

#1725 Update wrong rollup terser dependency
  package.json
  rollup.config.js
  yarn.lock
Labels: maintenance

#1735 Delete obsolete jest config
  jest.config.js
Labels: skip-changelog

#1737 Fix package exports
  package.json
  rollup.config.js
Labels: bug

#1743 feat: support facet distribution for federated search
  src/types/types.ts
  tests/search.test.ts
Labels: enhancement

#1739 Separate token specific code into its own export
  .code-samples.meilisearch.yaml
  package.json
  rollup.config.js
  src/browser.ts
  src/clients/browser-client.ts
  src/clients/node-client.ts
  src/index.ts
  src/meilisearch.ts
  src/token.ts
  src/types/types.ts
  tests/env/esm/src/index.js
  tests/env/node/index.js
  tests/env/typescript-browser/src/index.ts
  tests/env/typescript-node/package.json
  tests/env/typescript-node/src/index.ts
  tests/env/typescript-node/tsconfig.json
  tests/env/typescript-node/yarn.lock
  tests/keys.test.ts
  tests/token.test.ts
Labels: breaking-change

#1751 fix: pull the latest in the CI instead of forcing the v1.11
  .github/workflows/tests.yml
Labels: bug
