Repository meilisearch/meilisearch-js, pull requests merged in 2024-09, with the labels that each got.

#1698 Add `"packageManager"` entry to package.json
  package.json
Labels: maintenance

#1688 Remove cross-fetch dependency
  .github/dependabot.yml
  package.json
  rollup.config.js
  src/http-requests.ts
  tests/settings.test.ts
  tests/utils/meilisearch-test-utils.ts
  yarn.lock
Labels: breaking-change

#1712 Fix code samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#1710 Let dependabot create a single PR for multiple dependencies
  .github/dependabot.yml
Labels: skip-changelog
