Repository meilisearch/meilisearch-js, pull requests merged in 2024-12, with the labels that each got.

#1788 Update CONTRIBUTING.md with minimal Node version
  CONTRIBUTING.md
Labels: maintenance

#1801 Add 1.12 code samples
  .code-samples.meilisearch.yaml
Labels: maintenance

#1805 Remove mention of support of Node 14 and 16
  CONTRIBUTING.md
  README.md
Labels: documentation

#1795 Fix and improve `eslint` config, other minor changes
  eslint.config.js
  package.json
  rollup.config.js
  tests/errors.test.ts
  tests/search.test.ts
  tsconfig.build.json
  tsconfig.eslint.json
  tsconfig.json
Labels: maintenance

#1661 Improve `token.ts`
  .code-samples.meilisearch.yaml
  src/token.ts
  src/types/types.ts
  src/utils.ts
  tests/env/esm/src/index.js
  tests/env/node/index.js
  tests/env/typescript-browser/src/index.ts
  tests/env/typescript-node/src/index.ts
  tests/token.test.ts
Labels: breaking-change
