Repository meilisearch/meilisearch-js, pull requests merged in 2024-01, with the labels that each got.

#1622 Update Jest
  .eslintignore
  jest-disable-built-in-fetch.js
  jest.config.js
  package.json
  tests/__snapshots__/facet_search.test.ts.snap
  tests/__snapshots__/faceting.test.ts.snap
  tests/__snapshots__/get_search.test.ts.snap
  tests/__snapshots__/search.test.ts.snap
  tests/__snapshots__/settings.test.ts.snap
  yarn.lock
Labels: maintenance

#1619 feat: add proximity precision settings
  README.md
  src/indexes.ts
  src/types/types.ts
  tests/__snapshots__/settings.test.ts.snap
  tests/proximity_precision.test.ts
  tests/settings.test.ts
Labels: enhancement

#1623 Implement vector search experimental feature
  README.md
  src/indexes.ts
  src/types/types.ts
  tests/__snapshots__/settings.test.ts.snap
  tests/embedders.test.ts
  tests/get_search.test.ts
  tests/search.test.ts
Labels: enhancement

#1624 Add code samples v1.6.0
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#1627 fix: snapshots after removing embedders from default settings
  tests/__snapshots__/settings.test.ts.snap
Labels: maintenance

#1620 Update Node.js versions that are used in tests
  .github/workflows/meilisearch-prototype-tests.yml
  .github/workflows/pre-release-tests.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  bors.toml
Labels: breaking-change
