Repository meilisearch/meilisearch-js, pull requests merged in 2025-03, with the labels that each got.

#1848 Remove hint about bad Meilisearch version
  src/errors/index.ts
  src/errors/version-hint-message.ts
  src/indexes.ts
  tests/documents.test.ts
Labels: maintenance

#1847 Update Vite and Vitest
  package.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: dependencies, maintenance

#1741 Improve `HttpRequests`
  src/batch.ts
  src/http-requests.ts
  src/indexes.ts
  src/meilisearch.ts
  src/task.ts
  src/types.ts
  src/utils.ts
  tests/client.test.ts
  tests/dictionary.test.ts
  tests/search.test.ts
  tests/stop_words.test.ts
  tests/synonyms.test.ts
  tests/task.test.ts
  tests/unit.test.ts
  tests/utils/meilisearch-test-utils.ts
  tsconfig.json
Labels: bug, breaking-change, maintenance

#1861 Add `husky` and configure `lint-staged`
  .github/workflows/docs.yml
  .github/workflows/meilisearch-prototype-tests.yml
  .github/workflows/pre-release-tests.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  .husky/pre-commit
  .prettierrc.js
  CONTRIBUTING.md
  lint-staged.config.js
  package.json
  yarn.lock
Labels: maintenance

#1891 Implement the experimental feature for remote federated search requests.
  src/meilisearch.ts
  src/types.ts
  tests/client.test.ts
  tests/search.test.ts
Labels: enhancement

#1865 Fix `package.json` `"repository"` field
  package.json
Labels: maintenance

#1896 Remove BORS, enable merge queues in actions
  .github/release-draft-template.yml
  .github/workflows/tests.yml
  CONTRIBUTING.md
  README.md
  bors.toml
Labels: maintenance

#1749 Remove custom TypeScript ESLint rules and adapt code, fix `HttpRequests` issue where timeout errors sometimes weren't properly thrown
  eslint.config.js
  src/http-requests.ts
  src/indexes.ts
  src/meilisearch.ts
  src/token.ts
  src/types.ts
  tests/client.test.ts
  tests/documents.test.ts
  tests/errors.test.ts
  tests/faceting.test.ts
  tests/keys.test.ts
  tests/localized_attributes.test.ts
  tests/search.test.ts
  tests/search_cutoff_ms.test.ts
  tests/token.test.ts
  tests/utils/meilisearch-test-utils.ts
  yarn.lock
Labels: bug, maintenance
