Repository meilisearch/meilisearch-js, pull requests merged in 2025-04, with the labels that each got.

#1900 Update Vitest, ESLint and plugins, adapt code
  package.json
  tests/client.test.ts
  tests/unit.test.ts
  tests/utils/meilisearch-test-utils.ts
  yarn.lock
Labels: dependencies

#1912 Add v1.14.0 features
  .code-samples.meilisearch.yaml
  src/indexes.ts
  src/types/task_and_batch.ts
  src/types/types.ts
  tests/__snapshots__/facet_search.test.ts.snap
  tests/__snapshots__/settings.test.ts.snap
  tests/batch.test.ts
  tests/documents.test.ts
  tests/embedders.test.ts
  tests/facet_search.test.ts
  tests/filterable_attributes.test.ts
  tests/utils/meilisearch-test-utils.ts
Labels: enhancement

#1924 Remove _md code samples for Mintlify migration
  .code-samples.meilisearch.yaml
Labels: documentation
